name: Unzip Folder
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install unzip -y
      - run: ls -la 代码/  # 调试：确认文件存在
      - run: |
          unzip ./代码/inspectionProfiles.zip -d ./my-folder/ || echo "解压失败"
          [ -f ./代码/inspectionProfiles.zip ] && rm ./代码/inspectionProfiles.zip
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "自动提交解压文件" || echo "无新文件提交"
          git push
