name: 文件解压与修复
on: [push]

jobs:
  unzip:
    # ↓↓↓ 新增跳过检测 ↓↓↓
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: 安装工具
        run: sudo apt-get install unzip convmv -y

      - name: 解压文件
        run: unzip "代码/inspectionProfiles.zip" -d "my-folder/"

      - name: 修复文件名编码
        run: |
          convmv -f gbk -t utf8 --notest -r my-folder/
          find my-folder/ -name "*" -exec rename 's/[^[:print:]]//g' {} \;
        
      - name: 提交修复结果
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "自动修复系统"
          git config user.email "auto-repair@github.com"
          git add .
          git commit -m "修复文件编码"  # ← 移除了 [skip ci]
          git push
