name: Fix Encoding Unzip
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install tools
        run: sudo apt-get install -y p7zip-full convmv

      - name: Extract with encoding fix
        run: |
          7z x -o"my-folder/" -y "代码/inspectionProfiles.zip"
          convmv -f GBK -t UTF-8 --notest "my-folder/"*

      - name: Commit results
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Auto Fix"
          git config --global user.email "auto@github.com"
          git add .
          git commit -m "Fix filename encoding" || echo "No changes"
          git push
