name: Unzip Folder
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - run: sudo apt-get install unzip -y
      
      - run: |
          unzip 代码/inspectionProfiles.zip -d my-folder/

      
      - name: 提交变更
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git status
          git diff-index --quiet HEAD || git commit -m "自动提交解压文件"
          git push "https://${{ github.actor }}:$GH_TOKEN@github.com/${{ github.repository }}.git"
