name: Unzip Folder
on:
  push:
    paths:
      - './代码/inspectionProfiles.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install unzip -y  # 确保unzip工具存在
      - run: |
          unzip 代码/inspectionProfiles.zip -d my-folder/
          rm 代码/inspectionProfiles.zip
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add my-folder/
          git commit -m "自动提交解压文件"
          git push
