name: 中文文件名修复
on: [push]

jobs:
  chinese-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main  # 指定分支

      # 1. 安装专业中文编码工具
      - name: 安装编码工具包
        run: |
          sudo apt-get update
          sudo apt-get install -y unar convmv iconv python3
          pip install chardet
          
      # 2. 创建纯净解压环境
      - name: 纯净解压
        run: |
          rm -rf raw-files
          mkdir raw-files
          
          # 使用专用中文解压工具
          unar -e GBK -o raw-files/ "代码/inspectionProfiles.zip"
          
      # 3. 深度编码修复（双重验证）
      - name: 递归修复文件名
        run: |
          # 第一阶段修复：系统级转换
          convmv -f GBK -t UTF-8 --notest -r raw-files/
          
          # 第二阶段修复：Python精确处理
          python3 -c '
          import os, sys
          from chardet import detect
          
          def fix_encoding(path):
              for name in os.listdir(path):
                  fullpath = os.path.join(path, name)
                  
                  # 检测实际编码
                  with open(fullpath, "rb") as f:
                      raw_name = name.encode("latin1")
                      encoding = detect(raw_name)["encoding"] or "GBK"
                  
                  # 精确转换
                  try:
                      decoded = raw_name.decode(encoding)
                      fixed = decoded.encode("utf-8", "ignore").decode("utf-8")
                      if name != fixed:
                          os.rename(fullpath, os.path.join(path, fixed))
                  except Exception as e:
                      print(f"修复失败: {name} -> {e}")
          
          fix_encoding("raw-files")
          '
      
      # 4. 生成修复报告
      - name: 创建验证报告
        run: |
          echo "### 文件名修复验证报告" > encoding-report.md
          echo "| 原始文件名 | 修复后文件名 |" >> encoding-report.md
          echo "|------------|--------------|" >> encoding-report.md
          
          find raw-files -maxdepth 1 -type d | while read dir; do
            orig_name=$(basename "$dir" | iconv -f latin1)
            fixed_name=$(basename "$dir")
            echo "| $orig_name | $fixed_name |" >> encoding-report.md
          done
          
          # 移动修复后文件
          mv raw-files/* my-folder/
      
      # 5. 可视化验证
      - name: 生成文件树
        run: |
          tree my-folder/ --charset=Unicode -f > file-tree.txt
      
      - name: 上传验证文件
        uses: actions/upload-artifact@v3
        with:
          name: encoding-repair-results
          path: |
            encoding-report.md
            file-tree.txt
      
      # 6. 安全提交
      - name: 提交修复结果
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "中文编码修复系统"
          git config user.email "gbk-fix@github.com"
          git add .
          git commit -m "专业修复GBK/GB2312编码文件"
          git push
