name: Fix Encoding & Permissions
on: [push]

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限声明

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install unzip convmv -y

      - name: Unzip files
        run: |
          unzip "代码/inspectionProfiles.zip" -d "my-folder/" || echo "解压完成"

      - name: Fix filename encoding
        run: |
          convmv -f GBK -t UTF-8 --notest -r "my-folder/" 
          find "my-folder" -exec rename 's/[^a-zA-Z0-9_.\/-]//g' {} \;

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          REPO_URL="https://${{ github.actor }}:$GH_TOKEN@github.com/${{ github.repository }}.git"
          
          git add .
          git commit -m "自动修复编码 [skip ci]" || exit 0
          git push "$REPO_URL"
